# Détection de migrations scientifiques (pays de naissance ≠ affiliation)
  PREFIX dbo: <http://dbpedia.org/ontology/>
  PREFIX foaf: <http://xmlns.com/foaf/0.1/>
  PREFIX schema: <http://schema.org/>
  PREFIX db: <http://dbpedia.org/resource/>

  SELECT DISTINCT
    ?firstName
    ?lastName
    ?birthCountry 
    ?orgName 
    ?orgCountry

  WHERE {
    ?person a foaf:Person ;
            foaf:familyName ?lastName ;
            foaf:givenName ?firstName ;
            schema:birthPlace ?birthPlace ;
            schema:affiliation ?organization .

    ?birthPlace dbo:country ?birthCountry .

    ?organization schema:location ?orgLocation ;
                  foaf:name ?orgName .

    ?orgLocation dbo:country ?orgCountry .

    FILTER(?birthCountry != ?orgCountry)
    FILTER(?orgName != "nan")
  	FILTER(?birthCountry != db:nan)

  }

  ORDER BY ?personName

